spring:
  application:
    name: NotificationService
  cloud:
    function:
      web:
        path: /functions

server:
  port: 9097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: none



