spring:
  application:
    name: NotificationService
  cloud:
    function:
      definition: orderEventReceiver
      web:
        path: /functions
    stream:
      bindings:
        # configure spring cloud stream - receive order notification
        orderEventReceiver-in-0:
          destination: order.created
          contentType: application/json
          group: ${spring.application.name}
        # configure spring cloud stream - acknowledgement order notification
        orderEventReceiver-out-0:
          destination: order.ack
          contentType: application/json
          group: ${spring.application.name}





  # configure rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



server:
  port: 9097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: none



