server:
  port: 9098


spring:
  application:
    name: OrderService
  cloud:
    function:
      definition: consumeAck
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        orderCreatedEvent-out-0:
          destination: order.created
          contentType: application/json
          group: ${spring.application.name}
        consumeAck-in-0:
          destination: order.ack
          contentType: application/json
          group: ${spring.application.name}



  # configure rabbitMQ
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#        bindings:
#          # configure spring cloud stream - receive order notification
#          orderCreatedEvent-out-0:
#            destination: order.created
#            contentType: application/json
#            group: ${spring.application.name}
#          # configure spring cloud stream - receive order notification
#          consumeAck-in-0:
#            destination: order.ack
#            contentType: application/json
#            group: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
   env:
    enabled: true
  endpoint:
    shutdown:
      access: none



