spring:
  application:
    name: OrderService
  cloud:
    function:
      definition: consumeAck

    stream:
      bindings:
        # configure spring cloud stream - receive order notification
        orderCreatedEvent-out-0:
          destination: order.created
          contentType: application/json
          group: ${spring.application.name}
        # configure spring cloud stream - receive order notification
        consumeAck-in-0:
          destination: order.ack
          contentType: application/json
          group: ${spring.application.name}
  # configure rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# configure spring cloud stream



server:
  port: 9098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
   env:
    enabled: true
  endpoint:
    shutdown:
      access: none



