spring:
  application:
    name: OrderService

server:
  port: 9098

eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
   env:
    enabled: true
  endpoint:
    shutdown:
      access: true



