server:
  port: 9095


spring:
  application:
    name: GATEWAYSERVICE
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: ORDERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: NOTIFICATIONSERVICE
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/v1/notifications/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka